name: "setup prerequisites (shared steps)"
description: "Shared steps used to setup prerequisites for other jobs."
runs:
  using: "composite"
  steps:
    - name: "apt-get update"
      shell: sh
      run: sudo apt-get update
    # See https://github.com/Spotifyd/spotifyd/issues/659#issuecomment-737730954
    # and https://users.rust-lang.org/t/failed-to-run-custom-build-command-for-libudev-sys-v0-1-4/53926/2
    - name: "Install missing alsa and libudev dependencies"
      shell: sh
      run: sudo apt install librust-alsa-sys-dev libudev-dev
    - name: "Update rustup and Rust 'stable' toolchain"
      shell: sh
      run: rustup update stable
    - name: "Set Rust toolchain to 'stable'"
      shell: sh
      run: rustup default stable
    - name: "Install WASM target"
      shell: sh
      run: rustup target add wasm32-unknown-unknown
